apiVersion: v1
kind: ConfigMap
metadata:
  name: kuvryn-sync-e2e-config
  namespace: kuvryn-sync-e2e
  labels:
    app.kubernetes.io/name: kuvryn-sync-e2e
    test.sync.kuvryn.io/case: gh-end-to-end
data:
  version: v2
  source: github
